/**
 * تقرير هبّة payload — the shape `generate_habba_report` produces.
 *
 * Shared between the database (which builds it), the app (which shares it) and
 * the public page (which renders it). Kept in @habba/core so all three agree
 * on one definition rather than three drifting ones.
 */

export type ReportProvenance =
  'self_reported' | 'self_documented' | 'habba_verified' | 'third_party';

export interface ReportVehicle {
  readonly make_ar: string;
  readonly make_en: string;
  readonly model_ar: string;
  readonly model_en: string;
  readonly year: number;
  readonly plate: string | null;
  readonly vin: string | null;
  readonly colour: string | null;
  readonly current_mileage: number;
}

export interface ReportCoverage {
  readonly total: number;
  readonly habba_verified: number;
  readonly self_documented: number;
  readonly self_reported: number;
  readonly third_party: number;
}

export interface ReportEvent {
  readonly occurred_at: string;
  readonly recorded_at: string;
  readonly event_type: string;
  readonly provenance: ReportProvenance;
  readonly summary_ar: string;
  readonly summary_en: string;
  readonly mileage: number | null;
  readonly details: Readonly<Record<string, unknown>>;
  readonly attachment_count: number;
}

export interface ReportMileagePoint {
  readonly occurred_at: string;
  readonly mileage: number;
}

/** Evaluated at generation time, against the `generated_at` printed on the report. */
export type ReportWarrantyStatus = 'active' | 'expired';

export interface ReportWarranty {
  readonly service_ar: string;
  readonly service_en: string;
  readonly completed_at: string;
  readonly expires_at: string;
  readonly warranty_days: number | null;
  readonly status: ReportWarrantyStatus;
  /** Null once expired — there is nothing left to count down. */
  readonly days_remaining: number | null;
  /** A job already back under claim is an open question, not a reassurance. */
  readonly has_open_claim: boolean;
}

/** Thresholds are `score_to_recommendation` in migration 0026, not the renderer's. */
export type ReportRecommendation = 'buy' | 'negotiate' | 'avoid';

export interface ReportInspection {
  readonly completed_at: string;
  readonly template_ar: string;
  readonly template_en: string;
  readonly overall_score: number;
  /** Carried per row, so a frozen report keeps printing the scale it was scored on. */
  readonly score_scale: number;
  readonly recommendation: ReportRecommendation | null;
  readonly mileage_at_inspection: number | null;
}

/**
 * Payload versions:
 *
 * - **1** — 0014. No warranty state, no inspection scale.
 * - **2** — 0046. Adds `warranties` and `inspections`.
 *
 * Reports are frozen at generation (0014), so a version 1 payload exists
 * forever and will never grow the version 2 fields. They are optional here for
 * that reason and no other — a renderer must be able to tell "no warranties on
 * this car" from "this report predates warranty tracking", and printing
 * "لا يوجد ضمان" for the second would be a claim the data never made.
 * `carriesWarrantyAndScore()` is that check.
 */
export const REPORT_PAYLOAD_VERSION = 2;

export interface HabbaReport {
  readonly report_version: number;
  readonly generated_at: string;
  readonly vehicle: ReportVehicle;
  readonly ownership: { readonly months_on_habba: number };
  readonly chain: { readonly is_valid: boolean; readonly length: number };
  readonly coverage: ReportCoverage;
  readonly mileage_history: readonly ReportMileagePoint[];
  readonly events: readonly ReportEvent[];
  readonly warranties?: readonly ReportWarranty[];
  readonly inspections?: readonly ReportInspection[];
}

/**
 * Whether this payload was generated by a version that captured warranty state
 * and inspection scores at all.
 *
 * Checks the version rather than the presence of the arrays: an empty
 * `warranties` on a version 2 report is a real answer ("nothing is under
 * warranty"), and it must not read the same as an absent one.
 */
export function carriesWarrantyAndScore(report: HabbaReport): boolean {
  return report.report_version >= 2;
}

/**
 * Share of the history Habba itself produced, 0–1.
 *
 * This is the number the report leads with, and the reason it is honest to
 * lead with it: it is simultaneously the buyer's confidence signal and the
 * owner's reason to route the next service through Habba. See ADR-0005.
 */
export function verifiedRatio(coverage: ReportCoverage): number {
  if (coverage.total === 0) return 0;
  return coverage.habba_verified / coverage.total;
}

export function isVerifiedEntry(provenance: ReportProvenance): boolean {
  return provenance === 'habba_verified';
}
